name: Deploy to GitHub Pages Daily

on:
  schedule:
    - cron: '30 */4 * * *' # Runs every 4 hours at the 30th minute

env:
  REACT_APP_INITIAL_COUNT: 0 # Default value
  REACT_APP_WORDLE: 'nodata'
  REACT_APP_ELEC: 'nodata'
  REACT_APP_TEMP: 'nodata'
  INIT_COUNT: ${{ vars.REPO_INIT_CNT || 22 }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read a variable
        run: echo "My variable is $INIT_COUNT"
        env:
          INIT_COUNT: ${{ env.INIT_COUNT }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Update react env variables
        run: ./scripts/update_env.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build React app
        run: npm run build
        env:
          REACT_APP_INITIAL_COUNT: ${{ env.REACT_APP_INITIAL_COUNT }}
          REACT_APP_WORDLE: ${{ env.REACT_APP_WORDLE }}
          REACT_APP_ELEC: ${{ env.REACT_APP_ELEC }}
          REACT_APP_TEMP: ${{ env.REACT_APP_TEMP }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true