name: Deploy to GitHub Pages Daily

on:
  schedule:
    - cron: '44 22 * * *' # Runs every day at 00:30 EEST (Standard Time)

env:
  REACT_APP_INITIAL_COUNT: 0 # Default value

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Toggle REACT_APP_INITIAL_COUNT using bash script
        run: ./scripts/update_env.sh

      - name: Build React app
        run: npm run build
        env:
          REACT_APP_INITIAL_COUNT: ${{ env.REACT_APP_INITIAL_COUNT }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true